# Usamos a mesma imagem leve e estável do Nginx.
FROM nginx:stable-alpine

# Remove a configuração padrão do Nginx.
RUN rm /etc/nginx/conf.d/default.conf

# Copia nosso arquivo de configuração personalizado para o local correto.
# O Nginx irá carregar automaticamente qualquer arquivo .conf deste diretório.
COPY nginx.conf /etc/nginx/conf.d/default.conf


