# Utiliza a imagem oficial e leve do Nginx baseada em Alpine.
FROM nginx:stable-alpine

# Remove a configuração padrão do Nginx.
RUN rm /etc/nginx/conf.d/default.conf

# Copia o nosso ficheiro de configuração personalizado para o local correto dentro do contentor.
COPY nginx.conf /etc/nginx/conf.d/